default: &default
  adapter:    mysql2
  username:   root
  password:   mysql
  host:       127.0.0.1
  reconnect:  true

development:
  <<: *default
  database: hubrise_app_dev

test:
  <<: *default
  database: hubrise_app_test

